### ISSUE TITLE
various button related issues

### ISSUE THREAD

**Issue by cuvoodoo** [ataradov/open-5012h#2]
here a couple of issues I found while using the device:

- the menu button does not open a menu (the readme mentions this is where I can set the 1x/10x probe)
- pressing F2 freezes the device (the screen does not update anymore and other button presses have no effect)
- in calibration mode I am able to set the zero value, but pressing on the trigger up/down does not seem to change the corresponding calibration value in the delta, scale, and offset mode (at least nothing visible changes)

let me know if I should open separate issues for each point.
note that I did not look at the source code, but maybe you have a quick answer before I do that.
else I quite like your firmware. thanks for all the work.

**Comment by ataradov** [comment]
There is no menu, it was never implemented. There is also no 10x mode. It is a purely software thing, so I did not bother implementing it, since I don't really care about this device anymore. The hardware is just bad.

The freeze is intentional to make it easier to program the device. You can disable that in the main.c near a comment "// Debug only, makes it easier to program things"

The adjustments are done by looking at the trace. And there are specific modes that need to be used for various calibrations. For example, Delta calibration must be performed in 125 MSPS mode. You should see a real trace on one side of the screen and zoomed in version on the other side. You should clearly see even and odd samples move apart when adjusting the value.

**Comment by cuvoodoo** [comment]
thanks for the clarification about the buttons.
I was able to see the even/odd values.
